### ISSUE TITLE
what language to use for creating, registering, locating and storing digital content and their hashes? 

### ISSUE THREAD

**Issue by jhpoelen** [cboettig/contenturi#2]
In order to describe creating, registering and resolving (locating) content and their hashes, we need a consistent language/model.

I can think of three kind of actors:

1. a ContentRegistry - associates (temporary) content locations (e.g., URLs, DOIs) with the content they serve. The content is identified using content hashes. 

```
URI contentHash <- register(URI contentLocation)
Iterable<URI> contentLocations <- locationsOf(URI contentHash)
```

2. a ContentStore - puts and gets byte streams (i.e. content) using hash uris. 

```
InputStream is <- get(URI hashURI)
URI contentHash <- put(InputStream is)
```

3. a ContentHasher - take a byte stream and calculates some content hash uri. 
```
URI contentHash <- hash(InputStream is)
```

https://hash-archive.org is an example of a content location registry. A local repository can acts as a content registry and content store: register remote content with the local repository and the repository may also make the content available locally. 

A script that calculates a sha256 and turns it into a hash uri is an example of a content hasher.  

These three primitives are implement locally or remotely, are protocol independent and can be combined to implement a decentralized infrastructure to identify, publish (e.g., register + store.put) and retrieve (e.g., store.get) content. 

I was going back and forth between using "blob", "content" and "data". "blob" is probably most descriptive: "A Binary Large OBject (BLOB) is a collection of binary data stored as a single entity in a database management system." --- https://en.wikipedia.org/wiki/Binary_large_object . However, I think "blob" hashes sound funny, just like "blob" registries. Content hashes sounds friendlier to me and might appeal to a broader group. 

@cboettig I am curious to hear what you think about the model and the choice of language.

**Comment by cboettig** [comment]
Nice, I like this a lot, good statement of overall package scope & structure.

I want to think a bit more about function names / package API.  As written above suggests to me an object oriented design, where  `hashURI` etc objects with defined methods (`resolve.hashURI`, `get.hashURI`, etc).  While this could work, I think I'd prefer a the more 'functional programming' design that would let us treat `hashURI` as just a plain string of text and not some more attribute-laden object.  

### ContentRegistry

- I like the verb `register`, though maybe if it's not a `method.object` design this would become `register_uri`?    I like the overall design here of working with local or remote registries, though have to think a bit more about what it means to 'register' a local path.  (anyway, `register` is I think better name than the hash-archive.org endpoint name `enqueue`.)  
- `locationOf` doesn't feel great to me.  What's the natural verb that is the inverse operation of `register`?   I've been tossing around the idea of `resolve` (or `resolve_hash`).  

## ContentStore

This is great, lots to think about / understand for me in terms of implementation.  API-wise, I'm not sure about `put` and `get`, they seem a bit vague (`get` is also a namespace collision in R).  I wonder if can evoke their underlying functions (e.g. `put` is essentially either a `copy` or `download`) a bit better?  Particularly as in R at least we are used to using very different verbs for disk and memory operations, and these are disk-based operations.  

## Content hasher

So openssl R library already defines a family of `hashing` functions (see ?`hashing` ) rather nicely, with sensible options and semantic function names.  If in #1 we felt it was essential to support the abstract notion of a hashURI in any of the formats named there, then I'd be for defining a class for hashURI, but I'm also partial to the simplicity of telling a user the function is just `hash_uri` and it computes hashes in the format `hash://sha-256/xxx` only.


All of these functions have the question of return object format as well. as you know  hash-archive.org returns json with url, status, length (bytesize), timestamp, and type (inferred mimetype I think).  This is of course useful information, but I'm not quite sure how to handle it cleanly.  I think a common workflow would be to get a list of resolvable URIs given a list of hashes, so I'm kinda partial to functions like `register_uri` and `hash_uri` returning just a single hash uri string for each input they are given (e.g. to support vectorized workflows).  But I could see the advantage of returning all the other metadata, and I guess that makes the case for a return object type (or data.frame).  

anyway, just some preliminary thoughts and nit picks, I could be persuaded about any of the above too. Overall completely on board with this design and looking forward to your feedback.  I will also try hacking out something along these lines as I find the time and will no doubt have plenty of questions in the process.

**Comment by cboettig** [comment]
p.s. I like "content" over "blob".  It parallels the "content-based addressing" as the central organizing theme here, and I think it's a more familiar term to a researcher audience

**Comment by cboettig** [comment]
@jhpoelen Related t this, I'd love your thoughts over the verb `pin` and similar verbs defined in http://pins.rstudio.com/.  

In particular, `pin(URI)` as both a `put` and `get` function to a contentStore -- retrieving the local object if it exists, and otherwise downloading the object.  It looks like `pins` package does this by comparing the `eTag` of the remote resource to a registry of a local cache, but I think a similar workflow could apply here.  At very least, there's an interesting idea to me of being able to interact with the local contentStore with a single verb instead of two.  `pin` could take either a URI or hashURI, and would return the local path of the stored object.

**Comment by jhpoelen** [comment]
+1 on the functional design. I usage of ContentRegistry/Store/Hasher terms as a way to group functions by similar / inverse operations. 

Taking your suggestions, we'd have:

```R
# for content registry (a key-value store, where key is a hash-uri and the value is a list of known content locations)
# perhaps content locator?
some_hashuri <- register_content_by_location ( some_uri )
list_of_locations <- resolve_content_locations_of ( some_hashuri )

# for content store (or key-value store, where value is bunch of bytes or blobs, and key is a hashuri)
some_hashuri <- register_content ( bunch_of_bytes )
bunch_of_bytes <- resolve_content_of ( some_hashuri )

# hasher
some_hashuri <- content_hashuri_of ( bunch_of_bytes )
```

For more details (what is the data, where did it come from), I'd suggest to create a similar set of functions for content provenance:

```R
some_prov_hash_uri <- register_provenance ( bits_and_bytes_of_provenance_log )
list_of_prov_hash_uris <- provenance_of ( some_hash_uri )
```

but that is a whole separate topic. Perhaps worthy of another R package that uses this one.

btw - I like hashuri instead of hash-uri . The former sounds a bit like a yummy dish, whereas the latter is a bit more robotic.

**Comment by jhpoelen** [comment]
Hmm. HashURI is also https://www.w3.org/wiki/HashURI . 

About the pin - I can see how pin can make use of content registry / store internally. However, I am hesitant to reintroduce ambiguous/unreliable identifiers with ```pin (object, name)``` and ```pin_get(name)```. Also, ```pin(uri)``` still makes the reference to some content created at some point in time by some url: if you have a script that says: ```pin("https://example.org/the_latest_news")``` and you lose the association with the local pin-cache, you'd have an ambiguous reference. To me, pin is a bit like a browser cache: a temporary performance enhancement to work around bandwidth constraints.

**Comment by jhpoelen** [comment]
Perhaps content-uri  or content-hash-uri instead of hash-uri ?

**Comment by jhpoelen** [comment]
Some hacking in java (close your eyes!) 

```java
public interface ContentRegistry {

    /**
     *
     * @param uri location of content to be registered
     * @return hash of content produced by the provided URI
     */
    public URI register(URI uri);

    /**
     *
     * @param contentUri hash of registered content
     * @return known locations that produced content with provided content hash
     */
    public Stream<URI> locate(URI contentUri);
}

 public interface ContentStore {

    /**
     *
     * @param is stream of content to be stored
     * @return hash of stored content
     */
    public URI save(InputStream is);

    /**
     *
     * @param contentUri hash of requested content
     * @return stream of content with provided hash
     */
    public InputStream retrieve(URI contentUri);
}
```

I realize that the ContentHasher is implied.

**Comment by jhpoelen** [comment]
@cboettig so, I am circling back around to the "pin" idea. I can see how this might work, provided that you define the registry context appropriately and allow for returning the content provenance. 

so instead of:

```
mydata <- pin("https://example.org/dataset.tsv")
```

For populating a registry you'd say:
```R
doAnalysis <- function() {
# get the content, that's what most care about
# note that in the background, the registry is queried 
# and the pin returns the most recent data associated with the url
  mydata <- pin("https://example.org/dataset.tsv") 
  mydata_provenance <- pin_provenance("https://example.org/dataset.tsv")
  mydata_contenthash <- pin_hash("https://example.org/dataset.tsv")
  # do processing
  pin("results", results) 
}


# allow for pulling in new content in an open registry
registry::init(state = "populating") 

doAnalysis()

# publish the registry content somewhere local or remote
# on publication, the registry version is identified by a hash
registry_hash <- registry::publish()
```

Now, for others to reproduce:

```R
registry::init(state = "verifying", contentHash = "hash://sha256/2123fe...")

# re-run analysis - if results are registered by name that are not the same as the ones stored
# log an error and inform user that the results could not be reproduced.
results <- doAnalysis()
```

Likely that the pin package already does this, but I wanted to show how the pin idea is a simplified view of the registry concept. I think the key is to be able to reliably publish and reference a registry and its contents.

**Comment by cboettig** [comment]
Re naming, good call on the W3C hashURI.  I like content-uri.  I suppose one could call it `ni`, for "named information," the name proposed by [RFC6920](https://tools.ietf.org/html/rfc6920#section-3) for this operation (though as discussed, I'm not a fan either of the base64 encoding; particularly since I think base64 strings can use `/` which is confusing in a URI or directory context).  But I kinda like 'content-uri' better (the focus on 'content' resonates with me and I think for others as well).

**Comment by jhpoelen** [comment]
:+1:

**Comment by cboettig** [comment]
So for the ContentRegistry, I'm trying on `register()` and `lookup()` as the complementary operations, with the idea of supporting `local` and `remote` registries:

https://github.com/cboettig/contenturi/blob/b65b4b53897e68d2f3c3cce17bf29b16b756cd20/R/registry.R#L2-L10

Thoughts?

I'm also trying to wrap my head around the behavior for `local_register()`: in particular, does this function necessarily call the ContentStore routines to create a local copy?  If not, does it need an argument for what path / URL to associate with the storage?  (I guess the latter, since it is more flexible -- e.g. if I run my local store on a local server, I might want to convert the paths to URLs on the server's domain name and store those... or maybe that should be done by generalizing the `remote_registry` instead? or `remote_store`?


I've also taken a whack on the ContentStore API in `store.R`.  Currently I've called the two principle methods `store_uri`, and `retrieve_hash`, but these are probably not good names, at least not for the user-facing interface. Could be "store" and "retrieve", but I feel that's a bit too vague.  For the moment I'm not thinking of these as user-facing anyway, since we might collapse there role into `pin`, or maybe it is rolled up into local_registry and local_lookup?

**Comment by jhpoelen** [comment]
Cool to see our ideas getting materialized in code. I am following along with some implementation to see how it works in an existing code base (see https://github.com/globalbioticinteractions/globalbioticinteractions/tree/c9ae3ed02ba20eedf40972d033eed50b724a2ea3/eol-globi-cache/src/main/java/org/globalbioticinteractions/content ). 

For clarification around ContentRegistry and ContentStore, I found inspiration in https://wiki.ihe.net/index.php/Cross-Enterprise_Document_Sharing and their concept of DocumentSource, DocumentRegistry, DocumentStore and DocumentConsumer. 

Some general notes: 

1. Local Store/Registry - with this combo, I find it easy to conflate the registry actions (e.g., register / query) with store actions ( provideAndRegister / retrieve ). This would confuse the query (find location of the content) and retrieve (retrieve actual content) actions. But, in my mind, a store serves bytes and help register content and their provenance. The provenance is pass through. The idea is that content is meaningless unless it is registered and can be found somewhere, local and/or remote. 

2. Local Content Registry - a local registry uses the file system to associate a content uri (our "document id") with its content . Also, a registry keeps a provenance log to describe content provenance like dated location-contenturi association. In GloBI, I keep this log in a simple tsv file, in Preston, I keep this in a versioned rdf/nquad provenance log. Hash-archive keeps this in a leveldb database (see https://github.com/btrask/hash-archive ). 

3. Remote Content Registry - when registering content remotely - only the content provenance is registered (the content store saying: "hey, we have content here", similar to enqueue api of hash-archive). The twist here is that the registry actively verifies/establishes the identity of the content by retrieving the content at registered location and calculating the content-uri.  I imagine we'd want to query the remote registry by *any* content identifiers, including the crappy ones (e.g., urls). The registry returns the matching provenance of provided identifiers (e.g., a combo of the history and source api of hash-archive). 
 
3.  Pragmatic implementation - I agree that the "pin" would be the most pragmatic API to expose for now, as long as there's a way to "save" and "load" the state of the local registry+store using some  publishable digital (e.g., zip file with provenance log + content).   However, as you indicated, for sake of modular architecture and ease of testing, we'd keep implementations of local store and local registry, and their remote equivalents, separated internally.

Specific notes:

```register_local``` would take a content provenance "object" that contains a local file url (the location, probably relative to some shared file path), time created, size, type etc. It so happens to be that the Local Store uses content addressed storage, so, confusingly, the local file url already contains components of the content uri. A pragmatic  local registry implementation would probably just infer the content uri from the file path, rather than computing the hash again. 

```lookup_local```  this *registry* api would take both local, remote urls and content uris: the kitchen sink. The returned results are a list of content uris that are associated with the provided arguments. For searching by content uris and a single local content store, only a single result is expects if the content is known:

```json
{ 
 "request": "hash://sha256/abcd...",
 "response": [ 
   { "location": "file:///some/path/ab/cd/abcd...." , "content-uri": "hash://sha256/abcd...." } 
 ] 
} 
```
. For remote urls, there might be more:

```json
{ 
 "request": "https://example.org/the-latest-news",
 "response": [ 
   { "location": "https://example.org/the-latest-news" , "content-uri": "hash://sha256/ef12...." },
   { "location": "https://example.org/the-latest-news" , "content-uri": "hash://sha256/abcd...." } 
 ] 
} 
```
Then queries to local store are made by their content-uris. 

For the pin operation, you'd have some rule to pick a content-uri is multiple are associated with some url: most recent, or first.

**Comment by jhpoelen** [comment]
Results of local and remote registries can be combined if the queries and their results are expressed in rdf/nquads to make for a more flexible data format using a "fill in the blank" query:

request to remote registry:
```
<https://example.org/the-latest-news> <hasVersion> _:blank .
```
and then expand to query locally:
```
<https://example.org/the-latest-news> <hasVersion> <hash://sha256/ef12....> .
<_:blankB> <hasVersion> <hash://sha256/ef12....> .
<https://example.org/the-latest-news> <hasVersion> <hash://sha256/ef12....>.
<_:blankA> <hasVersion> <hash://sha256/ab12....> .
```
with local registry adding their response:
```
<https://example.org/the-latest-news> <hasVersion> <hash://sha256/ef12....> .
<file://some/path/ef/12/ef12....> <hasVersion> <hash://sha256/ef12....> .
<https://example.org/the-latest-news> <hasVersion> <hash://sha256/ef12....>.
<file://some/path/ab/12/ab12....> <hasVersion> <hash://sha256/ab12....> .
```

Note that the local registry adds local file urls associated with the requested hashes.

**Comment by jhpoelen** [comment]
@mielliott fyi for Preston inspired related discussion

**Comment by jhpoelen** [comment]
With this, the following registry "query" can be generated from a single http get for https://example.org/registry/https://example.org/the-latest-news : 

```
<https://example.org/the-latest-news> <hasVersion> _:blank .
```

or you can just http post the query itself. 

For content uris, you'd translate https://example.org/registry/hash://sha256/ab12... into:
```
<_:blank> <hasVersion> <hash://sha256/ab12...> .
```

This would relieve the user of figuring out whether a request uri is a content uri or some url.

**Comment by cboettig** [comment]
@jhpoelen Thanks for this, great stuff and exciting to see it come together.  

A few questions to clarify (using your numbers from above).


3. Remote Content Registry.  

Gonna start with this one first because I think it's the simplest and clearly defined by the behavior of hash-archive.org, which gives us two endpoints:

- `api/enqueue` takes a URL and computes 5 hashes, stores hashes, timestamp, mimetype, & filesize in the registry.  
- `api/sources` takes Content-URIs  (in any of the formats from #1) and returns all registered URLs, (with timestamps, mimetype, & filesize).  This endpoint can also take a URL, and return the content URI(s) registered at that URL (e.g. by looking it up from recorded registry, not computing any hashes).  

**Questions re Remote Content Registry**: 
- (a) `enqueue` and `sources` don't sound like good names for these operations to me.  Are we okay with `register` and `lookup` instead?
- (b) Currently the code calls the `hash-archive.org` endpoints explicitly. Would it be good to also implement this behavior independently in this R package?  Perhaps this moves us away from the terms "local" or "remote" -- i.e. this would be a 'registry-only' mode, that has no store, and thus also doesn't take local paths as input (or output).  

2. Local Content Registry

Still not entirely sure about what this means.  It could be: 
  - (a)  The same thing as 3b above i.e. registry-only system, doesn't take local file paths but keeps the registry local. 
  - (b) registry only, but happy to record file-paths as input. (Not sure what use it that would be. Could be an internal function that was only used when file paths were given from a store, which probably has nice, hash-based file paths.  registering a path like `~/tmp/iris.csv` seems silly).  
  - (c) a registry (like b) but also backed by a store, such that if you give it local file path, `~/tmp/iris.csv`, it hashes the file & registers the metadata (as it would with a URL), but is also moves the location into the store and records a 'canonical' path (or maybe just a key?) to the store.  (Also see: http://richfitz.github.io/storr/)
- (d) Like c, but records metadata/provenance beyond what was mentioned above.  

I've taken a stab at (2c) so far, but I'm a bit worried I'm conflating/entangling "store" and "registry".  

Also, I think it would be nice for the R package to provide a pluggable interface for how the registry and possibly also the store are actually serialized, e.g. again see the example of  http://richfitz.github.io/storr/.  

4. `pin` API. 

Yup, I agree this is more of a user-facing interface that would be built from the core operations to support common workflows.  So I'll plan to revisit that later, but want to get the registry & store operations down first.

**Comment by jhpoelen** [comment]
As discussed, created using https://sequencediagram.com - 

[LocalStoreLocalRegistry.txt](https://github.com/cboettig/contenturi/files/4202144/LocalStoreLocalRegistry.txt)
![LocalStoreLocalRegistry](https://user-images.githubusercontent.com/1084872/74492073-7c849480-4e82-11ea-9be3-47007a43e946.png)

**Comment by cboettig** [comment]
There's a lot covered in this thread now.  I think we've converged on the internal notions of "Registry" and "Store", and are converging on a set of four primary verbs, but not sure we've nailed down the precise behavior of those verbs yet (see my questions at the top of https://github.com/cboettig/contenturi/pull/9#issue-376392640 as well as @jhpoelen comments).  

I think it would be helpful to have separate threads for each of them, since I think we're much closer to resolving the questions around, say, `register()` than we are to `retrieve()`.  So I'll close this and try to capture where things stand as I see them.
